name: expense eks
on:
  workflow_dispatch:
    inputs:
      action:
        description: " apply or destroy ?"
        required: true
        type: choice
        options:
         - apply
         - destroy
jobs:  
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Copy Repo Files
      uses: actions/checkout@v5
    - name: Configure AWS Credentials 
      uses: aws-actions/configure-aws-credentials@v6.2.3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: setup terraform
      uses: hashicorp/setup-terraform@v3
    - name: terraform init, plan and apply
      run: |
        for MODULE in 10-vpc 20-security-group 30-bastion; do
          echo ">>> Processing $MODULE"
          terraform -chdir=$MODULE init
          terraform -chdir=$MODULE plan
          if [[ "${{ inputs.action }}" == apply ]]; then
            terraform -chdir=$MODULE apply -auto-approve
          fi
          # if [[ "${{inputs.action }}" == "destroy" ]]; then
          #   terraform -chdir=$MODULE destroy -auto-approve
          # fi
        done
    - name: terraform destroy
      run: |
        for MODULE in 30-bastion 20-security-group 10-vpc; do
          echo ">>> Destroying $MODULE"
          if [[ "${{inputs.action }}" == "destroy" ]]; then
            terraform -chdir=$MODULE destroy -auto-approve
          fi
        done

    # - name: terraform init & plan for VPC module
    #   run: |
    #     cd 10-vpc
    #     terraform init
    #     terraform plan
    # - name: terraform apply
    #   if: ${{ inputs.action == 'apply' }}
    #   run: |
    #     cd 10-vpc
    #     terraform apply -auto-approve
    # - name: terraform init & plan for SG module
    #   run: |
    #     cd 20-security-group
    #     terraform init
    #     terraform plan
    # - name: terraform apply
    #   if: ${{ inputs.action == 'apply' }}
    #   run: |
    #     cd 20-security-group
    #     terraform apply -auto-approve
 


      
    # # - name: VPC 
    # #   if: ${{ inputs.action == 'apply' }}
    # #   run: terraform apply -auto-approve
    # # - name: terraform apply
    # #   if: ${{ inputs.action == 'apply' }}
    # #   run: terraform apply -auto-approve
    # # # - name: terraform destroy
    # # #   if: ${{ inputs.action == 'destroy' }}
    # # #   run: terraform destroy -auto-approve